FROM httpd:2.4

MAINTAINER Francisco Suárez <fsuarezm@gmail.com>

COPY docker/apache/conf/httpd.conf /usr/local/apache2/conf/httpd.conf

RUN mkdir -p /usr/local/apache2/conf/sites/

#EXPOSE 80
#CMD ["httpd", "-D", "FOREGROUND"]
